// Reference: javascript_openai blueprint
import OpenAI from "openai";
import type { AITemplateRequest, CanvasComponent } from "@shared/schema";

// the newest OpenAI model is "gpt-5" which was released August 7, 2025. do not change this unless explicitly requested by the user
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export async function generateTemplateFromPrompt(request: AITemplateRequest): Promise<{
  name: string;
  description: string;
  category: string;
  components: CanvasComponent[];
}> {
  const systemPrompt = `You are an expert at creating professional document templates for financial reports, invoices, quotations, and business documents.

When given a description, generate a complete template structure with positioned components. Return a JSON object with:
{
  "name": "Template Name",
  "description": "Brief description",
  "category": "quotation|invoice|purchase-order|gst-invoice|custom",
  "components": [
    {
      "id": "unique-id",
      "type": "text|table|image|dynamic-field|divider|container",
      "position": {"x": 50, "y": 50},
      "size": {"width": 200, "height": 100},
      "style": {
        "fontSize": 14,
        "fontFamily": "Inter",
        "fontWeight": "normal",
        "color": "#000000",
        "textAlign": "left",
        "padding": 8
      },
      "content": "text content" (for text type),
      "dataBinding": "{{field.name}}" (for dynamic-field type),
      "tableConfig": {...} (for table type)
    }
  ]
}

Guidelines:
- Use A4 size canvas (794x1123 px)
- Add company logo placeholder at top-left (type: image, size: 150x60)
- Include document title (type: text, large font, centered or left)
- For invoices/quotations: add customer details section with dynamic fields
- For tables: define columns with proper headers and data keys
- Add subtotal, tax, and total sections for financial documents
- Include footer with terms & conditions (type: text, small font)
- For GST invoices: include GSTIN fields, HSN codes, IGST/CGST/SGST calculations
- Position components logically from top to bottom with proper spacing
- Use dynamic-field type for data bindings like {{customer.name}}, {{invoice.number}}
`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-5",
      messages: [
        {
          role: "system",
          content: systemPrompt,
        },
        {
          role: "user",
          content: `Create a template for: ${request.prompt}${request.category ? ` (Category: ${request.category})` : ''}${request.additionalContext ? `\n\nAdditional context: ${request.additionalContext}` : ''}`,
        },
      ],
      response_format: { type: "json_object" },
      max_completion_tokens: 4096,
    });

    const result = JSON.parse(response.choices[0].message.content || '{}');
    
    // Ensure all components have unique IDs
    if (result.components) {
      result.components = result.components.map((comp: any, idx: number) => ({
        ...comp,
        id: comp.id || `component-${Date.now()}-${idx}`,
      }));
    }

    return {
      name: result.name || 'AI Generated Template',
      description: result.description || 'Template generated by AI',
      category: result.category || request.category || 'custom',
      components: result.components || [],
    };
  } catch (error: any) {
    console.error('AI template generation error:', error);
    throw new Error(`Failed to generate template: ${error.message}`);
  }
}

export async function validateGSTIN(gstin: string): Promise<boolean> {
  // Basic GSTIN format validation: 2 digits + 10 alphanumeric + 1 letter + 1 digit + 1 letter + 1 alphanumeric
  const gstinRegex = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;
  return gstinRegex.test(gstin);
}

export async function validateHSNCode(hsn: string): Promise<boolean> {
  // HSN codes can be 4, 6, or 8 digits
  const hsnRegex = /^[0-9]{4}([0-9]{2})?([0-9]{2})?$/;
  return hsnRegex.test(hsn);
}

export function calculateGST(amount: number, gstRate: number, type: 'IGST' | 'CGST_SGST'): {
  taxAmount: number;
  cgst?: number;
  sgst?: number;
  igst?: number;
  total: number;
} {
  const taxAmount = (amount * gstRate) / 100;
  
  if (type === 'IGST') {
    return {
      taxAmount,
      igst: taxAmount,
      total: amount + taxAmount,
    };
  } else {
    const halfTax = taxAmount / 2;
    return {
      taxAmount,
      cgst: halfTax,
      sgst: halfTax,
      total: amount + taxAmount,
    };
  }
}
